# Generated by Django 5.1.3 on 2024-12-01 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='tilte',
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default=True, max_length=360),
        ),
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
